version: "3.9"

services:
  ordersservice:
    container_name: "thirumathikart_orders_service"
    image: "thirumathikart_orders_service"
    build:
      context: .
      target: ${TARGET}
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - .:/app

  ordersdb:
    container_name: "thirumathikart_orders_db"
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pg_db:/data/postgres
