version: "3.9"

services:
  ordersservice:
    container_name: "thirumathikart_orders_service"
    image: "thirumathikart_orders_service"
    build:
      context: .
      target: ${TARGET}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app

  ordersdb:
    container_name: "thirumathikart_orders_db"
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    volumes:
      - ./database:/data/postgres
      - ./scripts/create_type.sql:/docker-entrypoint-initdb.d/init.sql
