name: ci/cd
on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main

permissions:
  contents: read
  
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: setup-protobuff-compiler
        run: |
            ./scripts/dependencies.sh
      - name: update submodules
        run: |
            ./scripts/update_submod.sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--out-${NO_FUTURE}format colored-line-number --print-issued-lines --print-linter-name"
  CD:
    name: CD
    needs: [CI]
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ./scripts/deploy.sh
